---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-mongodb
  name: pttg-mongodb
spec:
  type: NodePort
  ports:
  - name: http
    port: 27017
    nodePort: 30702
    targetPort: http
  selector:
    name: pttg-mongodb
