#!/usr/bin/env bash

set -e

# check manually with the released docker artifact to see the version of kd and kubectl
# docker run --rm -ti --entrypoint=bash -v $PWD/kd:/kd -e ENVIRONMENT -e APP quay.io/ukhomeofficedigital/kd:${KD_VERSION}

VERSION=$1
ENVIRONMENT=$2
KD_BINARY='kd_linux_amd64'
KD_VERSION='v0.2.2'
KD_MD5='62a617785952e3ce0664795e1b1b5de6'
KD_DOWLOAD_ADDR="https://github.com/UKHomeOffice/kd/releases/download/${KD_VERSION}/kd_linux_amd64"
KUBECTL_BINARY='kubectl'
KUBECTL_VERSION='v1.3.5'
KUBECTL_MD5='26852c9bd750a2afee527658944397d1'
KUBECTL_DOWNLOAD_ADDR="https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
APP='pttg-mongodb'

function getKd() {
	echo "checking if the desired kd version exists"
	if [[ -e ${KD_BINARY} ]] && [[ $(md5sum ${KD_BINARY} | awk '{print $1}') = ${KD_MD5} ]];
	then
		echo "kd already exists locally and it is the wanted version, moving on ..."
	else
		echo "downloading kd version: ${KD_VERSION}"
		curl -sLO "${KD_DOWLOAD_ADDR}" && chmod a+x ./${KD_BINARY}
	fi
}

function getKubectl() {
	echo "checking if the desired kubectl version exists"
	if [[ -e ${KUBECTL_BINARY} ]] && [[ $(md5sum ${KUBECTL_BINARY} | awk '{print $1}') = ${KUBECTL_MD5} ]];
	then
		echo "kubectl already exists locally and it is the wanted version, moving on ..."
	else
		echo "downloading kubectl version: ${KUBECTL_VERSION}"
		curl -sLO "${KUBECTL_DOWNLOAD_ADDR}" && chmod a+x ./${KUBECTL_BINARY}
	fi
}

function archiveGitCommit() {
	GIT_COMMIT=${GIT_COMMIT:-$(git rev-parse --short HEAD)}
	GIT_COMMIT=${GIT_COMMIT:0:7}

	echo ${GIT_COMMIT} > GIT_COMMIT
	echo "deploy triggered by commit : ${GIT_COMMIT} on repo: ${GIT_URL} on branch ${GIT_BRANCH}"
	echo "deploying application version: $VERSION"

}

archiveGitCommit
getKd
getKubectl

export PATH=$PWD:$PATH

kubectl version --client

echo "deploying ..."
export VERSION
export ENVIRONMENT
./kd_linux_amd64 --context=pt-i-dev --namespace=pt-i-${ENVIRONMENT} --file kd/${ENVIRONMENT}/${APP}-deployment.yaml --file kd/${ENVIRONMENT}/${APP}-svc.yaml
